"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

"""
Django settings for myproject project.
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv # <-- Moved to top

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ---
# Load .env file from the project root (one level above this 'myproject' folder)
# This MUST be at the top, before settings are used.
# ---
load_dotenv(os.path.join(BASE_DIR, ".env"))


# ---
# SECRET KEY (CRITICAL SECURITY CHANGE)
# ---
# This pulls the key from Render's Environment Variables, NOT the file.
SECRET_KEY = os.environ.get('SECRET_KEY')


# ---
# DEBUG (CRITICAL SECURITY CHANGE)
# ---
# This will be 'False' on Render, but 'True' locally if you set DEBUG=True
DEBUG = os.environ.get('DEBUG', 'False') == 'True'


# ---
# ALLOWED HOSTS
# ---
# This automatically adds your Render website URL.
# It is safer than your teammate's '.onrender.com'
ALLOWED_HOSTS = []

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Add 'localhost' and '127.0.0.1' for local testing
ALLOWED_HOSTS.append('127.0.0.1')
ALLOWED_HOSTS.append('localhost')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic', # <-- ADD THIS for production
    'django.contrib.staticfiles',
    'mailinglist', 
    'api',         
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # <-- ADD THIS (near the top)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # ---
        # ADD paths to your template folders here
        # ---
        'DIRS': [
            BASE_DIR / 'api/templates',
            BASE_DIR / 'mailinglist/templates', # Added for your teammate
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# ---
# DATABASE (CRITICAL CHANGE)
# ---
# This uses Render's free Postgres database when on Render,
# but keeps your local db.sqlite3 for local testing.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# This 'if' statement is the magic.
# It checks if the DATABASE_URL (from Render) exists.
if 'DATABASE_URL' in os.environ:
    DATABASES['default'] = dj_database_url.parse(os.environ.get('DATABASE_URL'))


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ---
# STATIC FILES (For Whitenoise/Render)
# ---
STATIC_URL = 'static/'
# This is where 'collectstatic' will put files for production
STATIC_ROOT = BASE_DIR / 'staticfiles'
# This tells Render how to handle static files
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Your teammate's dotenv logic was moved to the top of the file.
